version: '2.1'
services:
#  datagen:
#    image: jark/datagen:0.1
#    command: "java -classpath /Users/taojiayun/zhiwei/project/flink-sql-training/datagen/flink-sql-demo.jar myflink.SourceGenerator --input /Users/taojiayun/zhiwei/project/flink-sql-training/datagen/user_behavior.log --output kafka kafka:9094 --speedup 2000"
#    depends_on:
#      - kafka
#    environment:
#      ZOOKEEPER_CONNECT: zookeeper
#      KAFKA_BOOTSTRAP: kafka
  mysql:
    image: jark/mysql-example:0.1
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
  elasticsearch:
    image: docker.io/library/elasticsearch:6.8.8
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
  kibana:
    image: docker.io/library/kibana:6.8.8
    ports:
      - "5601:5601"